language : cpp

cache: ccache

os: linux

addons: 
        apt:
                packages:
                        -g++
scripts:
        - g++ .travis.yml -o travis -Wall -Wextra -Werror -Wpedantic --std=c++17
        

        
